prompt Importing table JUGADORES_X_EQUIPO...
set feedback off
set define off
insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 1, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 2, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 3, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 5, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 6, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 7, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 8, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 9, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 10, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 11, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 12, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 13, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 14, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 16, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 17, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 18, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 19, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 20, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 21, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 22, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 23, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 25, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 26, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 27, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 28, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 29, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 30, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 31, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 1, 32, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 35, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 36, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 38, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 39, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 40, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 41, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 42, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 43, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 44, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 45, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 46, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 47, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 48, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 50, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 51, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 52, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 53, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 54, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 55, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 56, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 57, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 59, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 60, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 61, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 62, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 2, 63, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 65, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 66, 34);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 67, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 68, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 70, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 71, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 72, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 73, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 74, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 75, 33);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 76, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 77, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 78, 33);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 79, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 80, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 82, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 83, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 84, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 85, 32);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 86, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 87, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 88, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 89, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 90, 35);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 91, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 92, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 93, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 94, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 96, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 97, 32);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 98, 32);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 99, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 100, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 101, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 102, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 103, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 3, 104, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 106, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 107, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 108, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 109, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 111, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 112, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 113, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 114, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 115, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 116, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 117, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 118, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 119, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 120, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 121, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 122, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 123, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 125, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 126, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 127, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 128, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 129, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 130, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 131, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 132, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 133, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 134, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 135, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 137, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 138, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 139, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 140, 85);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 141, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 142, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 143, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 4, 144, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 146, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 147, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 149, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 150, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 151, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 152, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 153, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 154, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 155, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 156, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 158, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 159, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 160, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 161, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 162, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 163, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 164, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 165, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 166, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 167, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 168, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 170, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 171, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 172, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 173, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 174, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 175, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 5, 176, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 178, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 179, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 180, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 182, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 183, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 184, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 185, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 186, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 187, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 188, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 189, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 190, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 191, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 193, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 194, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 195, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 196, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 197, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 198, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 199, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 200, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 201, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 202, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 203, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 204, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 205, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 206, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 207, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 208, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 209, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 210, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 211, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 212, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 213, 31);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 214, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 215, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 217, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 218, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 219, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 220, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 221, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 222, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 223, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 6, 224, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 226, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 227, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 228, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 230, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 231, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 232, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 233, 33);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 234, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 235, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 236, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 237, 32);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 238, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 239, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 240, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 241, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 243, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 244, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 245, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 246, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 247, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 248, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 249, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 250, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 251, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 252, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 253, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 254, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 256, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 257, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 258, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 259, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 260, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 261, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 262, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 7, 263, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 265, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 266, 31);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 267, 33);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 269, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 270, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 271, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 272, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 273, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 274, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 275, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 277, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 278, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 279, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 280, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 281, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 282, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 283, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 284, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 285, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 286, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 287, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 289, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 290, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 291, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 292, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 293, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 294, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 8, 295, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 297, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 298, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 299, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 301, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 302, 31);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 303, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 304, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 305, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 306, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 307, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 308, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 309, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 311, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 312, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 313, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 314, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 315, 32);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 316, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 317, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 318, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 319, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 320, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 322, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 323, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 324, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 325, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 9, 326, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 328, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 329, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 330, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 331, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 333, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 334, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 335, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 336, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 337, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 338, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 339, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 340, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 341, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 342, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 344, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 345, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 346, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 347, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 348, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 349, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 350, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 351, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 352, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 353, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 355, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 356, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 357, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 358, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 359, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 10, 360, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 362, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 363, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 364, 33);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 366, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 367, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 368, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 369, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 370, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 371, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 372, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 373, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 375, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 376, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 377, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 378, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 379, 31);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 380, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 381, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 382, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 383, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 384, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 385, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 386, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 387, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 388, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 389, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 390, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 391, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 392, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 394, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 395, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 396, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 397, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 398, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 399, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 400, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 401, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 402, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 11, 403, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 405, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 406, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 408, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 409, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 410, 35);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 411, 31);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 412, 33);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 413, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 414, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 415, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 416, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 418, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 419, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 420, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 421, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 422, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 423, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 424, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 425, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 426, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 427, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 428, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 429, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 430, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 432, 34);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 433, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 434, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 435, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 436, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 12, 437, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 439, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 440, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 441, 33);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 442, 33);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 443, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 445, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 446, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 447, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 448, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 449, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 450, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 451, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 452, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 453, 33);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 454, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 456, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 457, 31);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 458, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 459, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 460, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 461, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 462, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 463, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 465, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 466, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 467, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 468, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 469, 32);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 470, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 471, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 13, 472, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 474, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 475, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 476, 34);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 477, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 479, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 480, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 481, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 482, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 483, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 484, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 485, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 487, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 488, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 489, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 490, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 491, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 492, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 493, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 494, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 495, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 496, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 497, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 498, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 499, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 500, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 501, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 502, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 504, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 505, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 506, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 507, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 508, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 509, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 510, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 14, 511, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 513, 33);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 514, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 515, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 517, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 518, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 519, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 520, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 521, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 522, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 523, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 524, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 525, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 526, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 528, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 529, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 530, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 531, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 532, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 533, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 534, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 535, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 536, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 537, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 539, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 540, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 541, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 542, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 543, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 544, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 545, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 15, 546, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 547, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 548, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 550, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 551, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 552, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 553, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 554, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 555, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 556, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 557, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 559, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 560, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 561, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 562, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 563, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 564, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 565, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 566, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 567, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 568, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 569, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 570, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 571, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 573, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 574, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 575, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 16, 576, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 578, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 579, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 581, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 582, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 583, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 584, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 585, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 586, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 587, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 589, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 590, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 591, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 592, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 593, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 594, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 595, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 596, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 597, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 598, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 599, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 601, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 602, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 603, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 604, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 605, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 606, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 607, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 608, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 609, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 610, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 17, 611, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 613, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 614, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 615, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 617, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 618, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 619, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 620, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 621, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 622, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 623, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 624, 34);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 625, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 626, 32);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 628, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 629, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 630, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 631, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 632, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 633, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 634, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 635, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 636, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 637, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 638, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 639, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 640, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 642, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 643, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 644, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 645, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 646, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 647, 31);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 18, 648, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 650, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 651, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 652, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 654, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 655, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 656, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 657, 32);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 658, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 659, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 660, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 661, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 662, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 664, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 665, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 666, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 667, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 668, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 669, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 670, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 671, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 672, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 673, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 674, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 675, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 677, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 678, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 679, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 680, 9);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 681, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 19, 682, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 684, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 685, 1);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 686, 25);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 687, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 688, 12);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 690, 18);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 691, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 692, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 693, 17);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 694, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 695, 28);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 696, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 697, 4);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 698, 2);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 699, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 700, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 701, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 702, 3);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 703, 27);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 705, 13);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 706, 19);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 707, 20);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 708, 5);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 709, 10);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 710, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 711, 11);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 712, 6);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 713, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 714, 26);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 715, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 716, 21);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 717, 14);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 718, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 719, 7);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 721, 24);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 722, 30);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 723, 29);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 724, 16);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 725, 23);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 726, 15);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 727, 54);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 728, 22);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 729, 8);

insert into JUGADORES_X_EQUIPO (ID_CAMPEONATO, ID_EQUIPO, ID_JUGADOR, NUMERO_CAMISETA)
values (1, 20, 730, 9);

prompt Done.
