prompt Importing table ANOTACION...
set feedback off
set define off
insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (1, 1, 210, 6, 6, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (2, 1, 644, 1, 26, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (3, 2, 137, 4, 17, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (4, 2, 125, 4, 11, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (5, 2, 119, 4, 16, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (6, 2, 141, 4, 17, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (7, 2, 79, 3, 40, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (8, 2, 83, 3, 28, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (9, 2, 98, 3, 40, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (10, 3, 518, 15, 3, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (11, 3, 57, 2, 38, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (12, 3, 46, 2, 29, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (13, 4, 371, 1, 39, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (14, 5, 679, 19, 4, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (15, 6, 416, 12, 30, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (16, 6, 308, 1, 40, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (17, 7, 21, 1, 13, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (18, 7, 160, 1, 35, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (19, 8, 602, 1, 25, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (20, 9, 502, 14, 7, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (21, 9, 466, 1, 27, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (22, 10, 330, 10, 42, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (23, 10, 329, 10, 30, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (24, 10, 334, 10, 37, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (25, 10, 553, 1, 33, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (26, 12, 472, 13, 37, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (27, 12, 458, 13, 23, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (28, 12, 699, 2, 27, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (29, 12, 694, 2, 25, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (30, 13, 50, 2, 9, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (31, 14, 574, 16, 8, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (32, 14, 565, 16, 45, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (33, 14, 553, 16, 17, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (34, 14, 241, 2, 25, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (35, 14, 250, 2, 38, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (36, 16, 585, 17, 21, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (37, 16, 681, 1, 14, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (38, 17, 299, 9, 15, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (39, 17, 309, 9, 11, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (40, 18, 163, 5, 28, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (41, 18, 122, 2, 44, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (42, 18, 123, 2, 37, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (43, 19, 626, 18, 18, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (44, 19, 640, 18, 27, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (45, 19, 519, 3, 20, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (46, 19, 517, 3, 35, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (47, 19, 528, 3, 17, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (48, 20, 379, 11, 28, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (49, 20, 381, 11, 16, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (50, 20, 201, 3, 8, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (51, 20, 180, 3, 36, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (52, 20, 182, 3, 10, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (53, 22, 419, 12, 12, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (54, 22, 406, 12, 46, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (55, 22, 172, 2, 7, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (56, 22, 155, 2, 8, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (57, 23, 673, 19, 36, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (58, 24, 262, 7, 43, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (59, 24, 313, 2, 3, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (60, 24, 303, 2, 10, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (61, 25, 699, 20, 20, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (62, 26, 526, 15, 40, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (63, 27, 132, 4, 26, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (64, 27, 126, 4, 6, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (65, 27, 266, 2, 14, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (66, 27, 281, 2, 33, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (67, 28, 594, 2, 9, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (68, 28, 606, 2, 25, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (69, 29, 89, 1, 29, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (70, 30, 206, 6, 13, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (71, 30, 560, 3, 35, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (72, 30, 562, 3, 20, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (73, 30, 562, 3, 27, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (74, 31, 628, 18, 39, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (75, 31, 642, 18, 35, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (76, 31, 364, 1, 24, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (77, 34, 510, 14, 7, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (78, 34, 697, 1, 9, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (79, 35, 38, 2, 6, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (80, 35, 62, 2, 45, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (81, 35, 41, 2, 45, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (82, 35, 661, 1, 40, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (83, 36, 165, 5, 39, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (84, 38, 111, 1, 44, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (85, 39, 298, 9, 18, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (86, 39, 303, 9, 3, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (87, 39, 201, 1, 35, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (88, 41, 514, 1, 1, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (89, 43, 232, 7, 17, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (90, 43, 168, 1, 16, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (91, 44, 107, 4, 1, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (92, 44, 470, 1, 35, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (93, 45, 677, 19, 21, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (94, 45, 680, 19, 11, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (95, 45, 481, 1, 2, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (96, 46, 7, 1, 28, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (97, 47, 540, 15, 38, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (98, 47, 539, 15, 1, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (99, 47, 700, 2, 17, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (100, 47, 688, 2, 4, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (101, 48, 647, 18, 30, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (102, 48, 629, 18, 7, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (103, 48, 305, 1, 41, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (104, 49, 82, 1, 7, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (105, 51, 384, 11, 44, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (106, 51, 372, 11, 10, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (107, 52, 427, 12, 44, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (108, 52, 601, 1, 23, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (109, 54, 159, 5, 29, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (110, 54, 202, 2, 8, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (111, 54, 202, 2, 37, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (112, 55, 491, 14, 17, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (113, 55, 482, 14, 22, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (114, 55, 487, 14, 32, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (115, 55, 17, 1, 16, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (116, 56, 53, 2, 2, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (117, 56, 52, 2, 14, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (118, 57, 281, 8, 41, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (119, 57, 281, 8, 17, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (120, 58, 303, 9, 15, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (121, 58, 313, 9, 7, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (122, 59, 726, 20, 45, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (123, 60, 425, 1, 34, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (124, 61, 93, 3, 26, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (125, 62, 557, 16, 9, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (126, 62, 540, 2, 17, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (127, 62, 529, 2, 46, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (128, 63, 599, 17, 19, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (129, 63, 340, 1, 19, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (130, 65, 12, 1, 29, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (131, 67, 91, 3, 34, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (132, 67, 89, 3, 11, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (133, 67, 42, 1, 7, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (134, 69, 114, 4, 17, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (135, 69, 111, 4, 43, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (136, 69, 128, 4, 22, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (137, 69, 476, 2, 4, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (138, 69, 480, 2, 38, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (139, 70, 12, 1, 43, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (140, 70, 27, 1, 13, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (141, 70, 688, 2, 14, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (142, 70, 684, 2, 15, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (143, 71, 283, 1, 26, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (144, 72, 76, 1, 8, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (145, 73, 550, 16, 31, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (146, 73, 308, 2, 10, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (147, 73, 306, 2, 22, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (148, 74, 666, 19, 27, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (149, 75, 419, 12, 1, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (150, 75, 410, 12, 20, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (151, 75, 414, 12, 18, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (152, 75, 52, 1, 11, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (153, 76, 156, 2, 32, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (154, 76, 168, 2, 42, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (155, 77, 359, 10, 8, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (156, 77, 448, 1, 29, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (157, 78, 249, 7, 30, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (158, 78, 226, 7, 15, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (159, 78, 581, 1, 27, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (160, 80, 270, 8, 7, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (161, 80, 274, 8, 40, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (162, 80, 287, 8, 41, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (163, 83, 80, 3, 21, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (164, 83, 83, 3, 11, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (165, 84, 121, 1, 14, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (166, 85, 272, 8, 35, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (167, 85, 280, 8, 2, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (168, 85, 267, 8, 7, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (169, 85, 275, 8, 16, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (170, 85, 633, 2, 32, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (171, 85, 624, 2, 31, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (172, 86, 377, 1, 26, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (173, 88, 513, 15, 17, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (174, 88, 515, 15, 34, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (175, 88, 302, 1, 6, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (176, 89, 32, 1, 11, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (177, 90, 475, 14, 25, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (178, 90, 509, 14, 11, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (179, 90, 419, 2, 30, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (180, 90, 430, 2, 22, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (181, 91, 603, 17, 37, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (182, 91, 608, 17, 41, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (183, 91, 206, 1, 24, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (184, 93, 520, 15, 13, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (185, 93, 513, 15, 30, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (186, 93, 533, 15, 4, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (187, 93, 26, 1, 18, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (188, 94, 204, 6, 31, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (189, 94, 206, 6, 41, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (190, 94, 462, 1, 17, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (191, 95, 340, 10, 33, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (192, 95, 350, 10, 44, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (193, 96, 387, 11, 5, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (194, 96, 386, 11, 10, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (195, 97, 668, 1, 3, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (196, 98, 428, 12, 25, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (197, 98, 425, 12, 13, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (198, 98, 408, 12, 22, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (199, 99, 244, 7, 16, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (200, 101, 77, 1, 29, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (201, 104, 722, 20, 15, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (202, 106, 170, 5, 41, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (203, 106, 150, 5, 29, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (204, 107, 674, 19, 8, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (205, 107, 430, 1, 17, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (206, 108, 108, 1, 13, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (207, 110, 41, 2, 11, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (208, 110, 44, 2, 37, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (209, 110, 184, 1, 39, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (210, 111, 290, 8, 5, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (211, 111, 292, 8, 20, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (212, 112, 468, 13, 17, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (213, 112, 462, 13, 31, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (214, 113, 508, 14, 22, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (215, 113, 494, 14, 21, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (216, 113, 490, 14, 7, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (217, 114, 701, 20, 31, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (218, 114, 722, 20, 33, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (219, 114, 330, 1, 46, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (220, 115, 76, 3, 28, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (221, 115, 97, 3, 45, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (222, 115, 518, 1, 28, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (223, 117, 44, 2, 26, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (224, 117, 299, 1, 45, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (225, 119, 101, 3, 34, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (226, 119, 94, 3, 33, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (227, 119, 87, 3, 26, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (228, 119, 19, 1, 30, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (229, 121, 648, 18, 43, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (230, 124, 51, 2, 7, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (231, 124, 579, 2, 24, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (232, 124, 598, 2, 3, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (233, 125, 9, 1, 40, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (234, 125, 20, 1, 23, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (235, 125, 313, 1, 14, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (236, 127, 370, 11, 27, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (237, 129, 700, 20, 29, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (238, 129, 566, 2, 40, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (239, 129, 568, 2, 37, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (240, 131, 311, 9, 32, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (241, 131, 312, 9, 18, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (242, 131, 316, 9, 36, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (243, 132, 505, 14, 8, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (244, 132, 498, 14, 18, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (245, 133, 406, 12, 3, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (246, 133, 435, 12, 36, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (247, 133, 272, 1, 17, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (248, 134, 610, 17, 11, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (249, 134, 586, 17, 38, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (250, 134, 244, 1, 10, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (251, 135, 97, 3, 34, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (252, 135, 67, 3, 14, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (253, 135, 70, 3, 15, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (254, 135, 106, 1, 38, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (255, 136, 670, 19, 18, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (256, 136, 664, 19, 27, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (257, 137, 48, 2, 45, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (258, 137, 50, 2, 21, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (259, 137, 55, 2, 33, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (260, 138, 525, 15, 12, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (261, 138, 537, 15, 29, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (262, 138, 202, 2, 32, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (263, 138, 191, 2, 7, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (264, 140, 556, 16, 43, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (265, 140, 584, 1, 39, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (266, 143, 622, 18, 19, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (267, 143, 636, 18, 32, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (268, 143, 630, 18, 5, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (269, 143, 61, 3, 25, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (270, 143, 53, 3, 20, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (271, 143, 45, 3, 40, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (272, 145, 307, 9, 40, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (273, 145, 315, 9, 6, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (274, 145, 298, 9, 34, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (275, 146, 154, 5, 29, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (276, 146, 90, 5, 35, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (277, 146, 86, 5, 18, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (278, 146, 65, 5, 38, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (279, 146, 84, 5, 18, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (280, 146, 75, 5, 16, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (281, 147, 187, 6, 34, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (282, 147, 191, 6, 31, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (283, 147, 477, 2, 36, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (284, 147, 481, 2, 14, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (285, 148, 448, 2, 42, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (286, 148, 457, 2, 15, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (287, 149, 125, 4, 16, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (288, 149, 139, 4, 22, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (289, 149, 139, 4, 40, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (290, 149, 111, 4, 32, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (291, 149, 532, 1, 37, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (292, 151, 194, 1, 15, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (293, 152, 44, 2, 19, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (294, 152, 57, 2, 5, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (295, 152, 62, 2, 3, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (296, 152, 390, 3, 30, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (297, 152, 369, 3, 6, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (298, 152, 366, 3, 9, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (299, 153, 488, 14, 3, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (300, 153, 483, 14, 18, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (301, 153, 613, 3, 34, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (302, 153, 645, 3, 35, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (303, 153, 634, 3, 30, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (304, 155, 603, 17, 20, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (305, 156, 468, 13, 22, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (306, 157, 114, 4, 27, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (307, 157, 121, 4, 1, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (308, 157, 142, 4, 10, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (309, 157, 436, 1, 44, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (310, 159, 239, 1, 34, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (311, 160, 539, 15, 16, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (312, 162, 104, 3, 28, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (313, 162, 90, 3, 23, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (314, 164, 164, 5, 21, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (315, 164, 163, 5, 2, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (316, 164, 149, 5, 14, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (317, 164, 149, 3, 34, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (318, 164, 289, 3, 8, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (319, 164, 274, 3, 46, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (320, 166, 241, 7, 12, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (321, 166, 10, 1, 14, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (322, 167, 119, 1, 33, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (323, 168, 305, 9, 23, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (324, 170, 652, 19, 37, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (325, 170, 618, 2, 44, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (326, 170, 629, 2, 2, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (327, 171, 284, 8, 40, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (328, 172, 507, 14, 2, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (329, 172, 484, 14, 45, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (330, 172, 574, 1, 19, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (331, 173, 119, 4, 42, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (332, 173, 130, 4, 2, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (333, 173, 109, 4, 38, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (334, 174, 161, 2, 7, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (335, 174, 167, 2, 4, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (336, 175, 3, 1, 7, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (337, 175, 3, 1, 39, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (338, 176, 76, 2, 14, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (339, 176, 76, 2, 26, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (340, 177, 337, 10, 14, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (341, 177, 356, 10, 28, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (342, 177, 351, 10, 32, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (343, 177, 411, 2, 13, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (344, 177, 421, 2, 4, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (345, 179, 595, 2, 18, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (346, 179, 590, 2, 43, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (347, 181, 550, 16, 16, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (348, 181, 690, 1, 12, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (349, 182, 299, 9, 34, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (350, 182, 298, 9, 42, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (351, 182, 306, 9, 43, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (352, 183, 174, 5, 12, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (353, 183, 174, 5, 44, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (354, 184, 666, 1, 29, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (355, 185, 195, 6, 31, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (356, 185, 214, 6, 38, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (357, 185, 118, 2, 23, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (358, 185, 108, 2, 22, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (359, 186, 541, 15, 43, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (360, 186, 543, 15, 35, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (361, 186, 519, 15, 22, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (362, 186, 521, 15, 23, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (363, 186, 546, 15, 25, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (364, 189, 658, 19, 42, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (365, 189, 559, 1, 21, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (366, 190, 36, 2, 45, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (367, 190, 172, 2, 24, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (368, 190, 158, 2, 6, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (369, 191, 158, 3, 6, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (370, 191, 295, 3, 39, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (371, 191, 283, 3, 5, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (372, 193, 127, 4, 34, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (373, 195, 17, 1, 17, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (374, 196, 423, 12, 3, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (375, 196, 430, 12, 36, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (376, 197, 357, 10, 6, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (377, 197, 348, 10, 36, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (378, 197, 345, 10, 14, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (379, 200, 544, 1, 46, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (380, 202, 68, 3, 45, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (381, 202, 76, 3, 21, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (382, 202, 94, 3, 37, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (383, 203, 317, 9, 40, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (384, 203, 303, 9, 28, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (385, 203, 320, 9, 34, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (386, 204, 443, 2, 14, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (387, 204, 461, 2, 21, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (388, 205, 415, 2, 13, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (389, 205, 428, 2, 21, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (390, 206, 265, 8, 29, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (391, 206, 279, 8, 37, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (392, 206, 290, 8, 15, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (393, 206, 46, 1, 23, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (394, 207, 23, 1, 5, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (395, 208, 160, 5, 19, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (396, 208, 170, 5, 31, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (397, 208, 476, 1, 37, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (398, 209, 382, 11, 20, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (399, 209, 381, 11, 7, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (400, 209, 128, 1, 35, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (401, 211, 75, 1, 6, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (402, 212, 533, 15, 1, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (403, 212, 466, 1, 8, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (404, 213, 359, 10, 40, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (405, 213, 358, 10, 13, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (406, 214, 121, 4, 6, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (407, 214, 133, 4, 42, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (408, 214, 564, 1, 23, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (409, 215, 435, 12, 41, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (410, 215, 427, 12, 25, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (411, 215, 414, 12, 32, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (412, 215, 415, 12, 15, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (413, 216, 249, 7, 16, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (414, 217, 501, 14, 34, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (415, 217, 510, 14, 2, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (416, 217, 274, 1, 41, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (417, 220, 303, 9, 8, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (418, 220, 109, 2, 12, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (419, 220, 119, 2, 13, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (420, 222, 387, 11, 13, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (421, 222, 358, 1, 7, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (422, 223, 570, 16, 14, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (423, 223, 561, 16, 26, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (424, 224, 453, 13, 7, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (425, 225, 161, 5, 31, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (426, 225, 659, 2, 38, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (427, 225, 667, 2, 7, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (428, 227, 611, 17, 37, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (429, 228, 526, 4, 34, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (430, 228, 536, 4, 43, 2);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (431, 228, 537, 4, 28, 1);

insert into ANOTACION (ID_ANOTACION, ID_JUEGO, ID_JUGADOR, ID_EQUIPO_ANOTADOR, MINUTO, TIEMPO)
values (432, 228, 530, 4, 25, 1);

prompt Done.
